### ISSUE TITLE
installing error : PIC register clobbered by ebx in asm

### ISSUE THREAD

**Issue by ghost** [Level/level-rocksdb#2]
i think the problem because of this : https://github.com/facebook/rocksdb/issues/70 so what this mean ...

---

 ../deps/leveldb/leveldb-rocksdb/util/crc32c.cc:328:57: error: PIC register clobbered by âebxâ in âasmâ
 **asm**("cpuid" : "=c"(c_), "=d"(d_) : "a"(1) : "ebx");
 ^
 ../deps/leveldb/leveldb-rocksdb/util/crc32c.cc:328:57: error: PIC register clobbered by âebxâ in âasmâ
 **asm**("cpuid" : "=c"(c_), "=d"(d_) : "a"(1) : "ebx");
 ^
 ../deps/leveldb/leveldb-rocksdb/util/crc32c.cc:328:57: error: PIC register clobbered by âebxâ in âasmâ
 **asm**("cpuid" : "=c"(c_), "=d"(d_) : "a"(1) : "ebx");
 ^
 make: **\* [Release/obj.target/leveldb/deps/leveldb/leveldb-rocksdb/util/crc32c.o] Error 1

**Comment by ralphtheninja** [comment]
Most likely outdated. There are prebuilts for linux, windows and osx.
