### ISSUE TITLE
License at the bottom should say level-rocksdb

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-rocksdb#35]

**Comment by vweevers** [comment]
IMO we don't need that text at all. I'm really happy with the succinct format I landed on in https://github.com/Level/level-js/pull/141:

```md
## License

[MIT](./LICENSE.md) © 2012-present [Max Ogden](https://github.com/maxogden) and [Contributors](./CONTRIBUTORS.md).
```

Renders as:

## License

[MIT](./LICENSE.md) © 2012-present [Max Ogden](https://github.com/maxogden) and [Contributors](./CONTRIBUTORS.md).

**Comment by ralphtheninja** [comment]
Cool. Lets do this.
