### ISSUE TITLE
Availability of the Write Ahead Log

### ISSUE THREAD

**Issue by nathanielse** [Level/level-rocksdb#68]
Hello,

I'm exploring the *level-rocksdb* and *RocksDB*. RocksDB can [store a change to its database in a write ahead log](https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log#overview) to prevent the loss of data if the process crashes.  Is the feature available ? 

Thank you for the creation of the library

**Comment by vweevers** [comment]
It's enabled by default IIRC.

**Comment by nathanielse** [comment]
Thank you
